version: "3"

services:
    webserver:
        image: "konstatinkorobitsin/bitrix-php:v1.5"
        container_name: webserver
        restart: always
        ports:
            - 8888:80
        volumes:
            - "./application/:/var/www"
            - "./application/public/:/var/www/html"
            - "./configs/php/php.ini:/usr/local/etc/php/php.ini"
            - "./configs/apache/apache2.conf:/etc/apache2/apache2.conf"

    database:
        image: mariadb:10.6.4
        container_name: database
        restart: always
        environment:
            MYSQL_DATABASE: "${DB}"
            MYSQL_USER: "${DB_USER}"
            MYSQL_PASSWORD: "${DB_PASS}"
            MYSQL_RANDOM_ROOT_PASSWORD: 'yes'
        volumes:
            - "db_volume:/var/lib/mysql"
            - "./configs/mysql/log/general-query.log:/var/log/mysql/general-query.log"
            - "./configs/mysql/log/slow-query.log:/var/log/mysql/slow-query.log"
            - "./configs/mysql/my.cnf:/etc/mysql/conf.d/my.cnf"

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: phpmyadmin
        links:
          - database
        depends_on:
          - database
        environment:
          PMA_HOST: db
          PMA_PORT: 3306
          PMA_ARBITRARY: 1
        restart: always

volumes:
    db_volume:
